#!/bin/busybox sh
mount -t proc proc /proc
printf 'THES:M:42\n'
IFS= read -r command </dev/ttyS0
if [ "$command" = ping ]; then
    echo 'serial command accepted'
else
    echo 'serial command rejected'
fi
ip link set eth0 up
ip addr add 10.0.0.1/24 dev eth0
sleep 1
if ping -c 1 -W 3 10.0.0.2; then
    echo 'ping passed'
else
    echo 'ping failed'
fi
poweroff -f
