#!/bin/busybox sh
mount -t proc proc /proc
ip link set eth0 up
ip addr add 10.0.0.1/24 dev eth0
sleep 1
if ping -c 1 -W 3 10.0.0.2; then
    echo 'ping passed'
else
    echo 'ping failed'
fi
poweroff -f
