#!/bin/busybox sh
mkdir -p /proc /dev
mount -t proc proc /proc
mount -t devtmpfs devtmpfs /dev
/bin/busybox stty -F /dev/ttyS0 -echo -opost
echo started
echo THES:M:42
read -r command < /dev/ttyS0
[ "$command" = finish ] || exit 1
echo finished
reboot -f
