FROM debian:bookworm-slim@sha256:88200866dfff7ea7f5cbcb6ec7c8a701889efe6fe859fe64d6990e4b07ea4171
COPY work/classifier /usr/local/bin/classifier
COPY work/ready /usr/local/bin/ready
CMD ["/usr/local/bin/ready"]
