FROM debian:bookworm-slim@sha256:88200866dfff7ea7f5cbcb6ec7c8a701889efe6fe859fe64d6990e4b07ea4171
COPY work/classify /usr/local/bin/classify
COPY work/classify.theseus-coverage.json /usr/local/share/classify.theseus-coverage.json
CMD ["/bin/sleep", "infinity"]
