#!/bin/busybox sh
set -eu
/bin/busybox mkdir -p /dev
/bin/busybox mount -t devtmpfs devtmpfs /dev
/bin/busybox stty -echo -opost </dev/ttyS0
printf 'THES:M:42\n' >/dev/ttyS0
IFS= read -r measurement </dev/ttyS0
printf 'sensor reading: %s\n' "$measurement" >/dev/ttyS0
printf 'urandom: '
/bin/busybox od -An -N16 -tx1 /dev/urandom
printf 'random: '
/bin/busybox od -An -N16 -tx1 /dev/random
/bin/busybox reboot -f
